// balac-react/examples/redux-master-examples/counter/Counter.js
import React, { Component } from 'react';
import PropTypes from 'prop-types';

class Counter extends Component {
	constructor (props) {
		super(props);
		this.incrementAsync = this.incrementAsync.bind(this);
		this.incrementIfOdd = this.incrementIfOdd.bind(this);
	}
	render () {
		const { value, onIncrement, onDecrement } = this.props;

		return (
			<p>Clicked: { value } times
				{' '}<button onClick={ onIncrement }> + </button>
				{' '}<button onClick={ onDecrement }> - </button>
				{' '}<button onClick={ this.incrementIfOdd }> Increment if odd </button>
				{' '}<button onClick={ this.incrementAsync }> Increment async </button>
			</p>
		);
	}
	incrementIfOdd () {
		if (this.props.value % 2 !== 0) {
			this.props.onIncrement();
		}
	}
	incrementAsync () {
		setTimeout(this.props.onIncrement, 1000);
	}
}

Counter.propTypes = {
	value: PropTypes.number.isRequired,
	onIncrement: PropTypes.func.isRequired,
	onDecrement: PropTypes.func.isRequired
};

export default Counter;

// balac-vue/Vue-Balac/vue 待整理/vue-cli-template/build issues/src/components/vuexs/Counter.vue
<template>
	<div class="counter">

		Clicked: {{ $store.state.count }} times, count is {{ evenOrOdd }}.

		<div>
			<button @click="increment">+</div>
			<button @click="decrement">-</div>
			<!-- <button @click="incrementIfOdd">Increment if odd</button>
    		<button	@click="incrementAsync">Increment async</button>-->
		</div>
	

	</div>
</template>
<script>

import { mapGetters, mapActions } from 'vuex';

export default {
	computed: mapGetters([
		'evenOrOdd'
	]),
	methods: mapActions([
		'increment',
		'decrement',
		'incrementIfOdd',
		'incrementAsync'
	])
};

</script>
